import type { NextPage } from "next";
import { useState, useRef } from "react";
import Head from "next/head";
import CodeEditor from "../components/CodeEditor";
import ConversationDisplay from "../components/ConversationDisplay";
import { CodeEditorContextProvider } from "../context/CodeEditorContext";
import { PromptConversationContextProvider } from "../context/PromptConversationContext";
import styles from "../styles/Playground.module.scss";

const Playground: NextPage = () => {
    let editorRef = useRef(null);
    // const [refLoaded, setRefLoaded] = useState(false);
    // function setRef(ref: any) {
    //     console.log("setting the ref", ref, editorRef);
    //     editorRef = ref;
    //     console.log(editorRef, "this is the editor ref");
    //     setRefLoaded(true);
    // }
    return (
        <CodeEditorContextProvider>
            <PromptConversationContextProvider>
                <div className={styles.container}>
                    <Head>
                        <title>Code Ghost Playground</title>
                        <meta
                            name="description"
                            content="Generated by create next app"
                        />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <main className={styles.main}>
                        <CodeEditor ref={editorRef} />
                        <ConversationDisplay ref={editorRef} />
                    </main>

                    <footer className={styles.footer}></footer>
                </div>
            </PromptConversationContextProvider>
        </CodeEditorContextProvider>
    );
};

export default Playground;
